#!/usr/bin/env python3
"""Build Tribunal skin mesh kit (humanoids + weapons) as OBJ for import/reference."""
import bpy
from pathlib import Path

OUT = Path("/home/buidl/ForgeStudio/games/tribunal/assets/models/skins")
OUT.mkdir(parents=True, exist_ok=True)


def clear():
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)


def mat(name, col, metallic=0.1, rough=0.5):
    m = bpy.data.materials.new(name)
    m.use_nodes = True
    b = m.node_tree.nodes.get("Principled BSDF")
    b.inputs[0].default_value = (*col, 1)
    if "Metallic" in b.inputs:
        b.inputs["Metallic"].default_value = metallic
    if "Roughness" in b.inputs:
        b.inputs["Roughness"].default_value = rough
    return m


def cube(name, loc, scale, color, metallic=0.1, rough=0.5):
    bpy.ops.mesh.primitive_cube_add(size=1, location=loc)
    o = bpy.context.active_object
    o.name = name
    o.scale = scale
    o.data.materials.append(mat(name, color, metallic, rough))
    return o


def humanoid(path: Path, body, accent, metal):
    clear()
    cube("torso", (0, 0, 1.1), (0.45, 0.28, 0.55), body)
    cube("head", (0, 0, 1.72), (0.28, 0.28, 0.28), body)
    cube("pad_l", (-0.42, 0, 1.4), (0.2, 0.12, 0.25), accent, 0.3, 0.4)
    cube("pad_r", (0.42, 0, 1.4), (0.2, 0.12, 0.25), accent, 0.3, 0.4)
    cube("leg_l", (-0.15, 0, 0.45), (0.14, 0.14, 0.5), body)
    cube("leg_r", (0.15, 0, 0.45), (0.14, 0.14, 0.5), body)
    cube("arm_l", (-0.42, 0, 1.05), (0.11, 0.11, 0.42), body)
    cube("arm_r", (0.42, 0, 1.05), (0.11, 0.11, 0.42), body)
    cube("belt", (0, 0, 0.78), (0.48, 0.2, 0.08), metal, 0.7, 0.35)
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.wm.obj_export(filepath=str(path), export_selected_objects=True)
    print("wrote", path)


def weapon_sword(path: Path, blade, grip):
    clear()
    cube("blade", (0, 0, 0.75), (0.05, 0.02, 0.95), blade, 0.85, 0.25)
    cube("guard", (0, 0, 0.28), (0.32, 0.06, 0.06), grip, 0.5, 0.4)
    cube("hilt", (0, 0, 0.1), (0.05, 0.05, 0.22), grip, 0.1, 0.8)
    cube("pommel", (0, 0, -0.05), (0.08, 0.08, 0.08), blade, 0.7, 0.3)
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.wm.obj_export(filepath=str(path), export_selected_objects=True)
    print("wrote", path)


def weapon_axe(path: Path, blade, grip):
    clear()
    cube("haft", (0, 0, 0.5), (0.06, 0.06, 1.0), grip, 0.1, 0.85)
    cube("head", (0.22, 0, 0.95), (0.45, 0.08, 0.28), blade, 0.7, 0.35)
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.wm.obj_export(filepath=str(path), export_selected_objects=True)
    print("wrote", path)


def weapon_dagger(path: Path, blade, grip):
    clear()
    cube("blade", (0, 0, 0.4), (0.04, 0.02, 0.55), blade, 0.8, 0.22)
    cube("hilt", (0, 0, 0.08), (0.06, 0.06, 0.18), grip, 0.1, 0.8)
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.wm.obj_export(filepath=str(path), export_selected_objects=True)
    print("wrote", path)


def main():
    skins = {
        "crimson": ((0.72, 0.14, 0.12), (0.95, 0.35, 0.2), (0.55, 0.5, 0.45)),
        "azure": ((0.18, 0.35, 0.78), (0.35, 0.65, 1.0), (0.5, 0.55, 0.65)),
        "bone": ((0.85, 0.8, 0.7), (0.55, 0.15, 0.15), (0.7, 0.65, 0.55)),
        "iron": ((0.35, 0.36, 0.38), (0.9, 0.55, 0.15), (0.65, 0.68, 0.72)),
    }
    for name, (body, accent, metal) in skins.items():
        humanoid(OUT / f"char_{name}.obj", body, accent, metal)

    weapon_sword(OUT / "wpn_sword_steel.obj", (0.78, 0.8, 0.85), (0.25, 0.15, 0.1))
    weapon_sword(OUT / "wpn_sword_blood.obj", (0.55, 0.12, 0.12), (0.15, 0.08, 0.08))
    weapon_axe(OUT / "wpn_axe_bronze.obj", (0.7, 0.48, 0.22), (0.3, 0.18, 0.1))
    weapon_dagger(OUT / "wpn_dagger_obsidian.obj", (0.08, 0.08, 0.12), (0.2, 0.05, 0.15))

    (OUT / "SKINS.md").write_text(
        "# Tribunal Skin Kit\n\n"
        "Generated by tools/scripts/build_skin_kit.py\n\n"
        "## Characters\n"
        "- char_crimson / azure / bone / iron\n\n"
        "## Weapons\n"
        "- wpn_sword_steel, wpn_sword_blood, wpn_axe_bronze, wpn_dagger_obsidian\n",
        encoding="utf-8",
    )
    print("skin kit complete ->", OUT)


if __name__ == "__main__":
    main()
