#!/usr/bin/env python3
"""SYS-ASSETS: headless Blender export of Tribune slice proxy meshes to glTF.

Usage:
  blender --background --python tools/scripts/export_slice_proxies.py

Outputs under assets/imported/tribune_proxies/ (cm scale for UE).
"""
from __future__ import annotations

import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "assets" / "imported" / "tribune_proxies"
OUT.mkdir(parents=True, exist_ok=True)


def export_with_blender() -> None:
    import bpy  # type: ignore

    def clear():
        bpy.ops.object.select_all(action="SELECT")
        bpy.ops.object.delete(use_global=False)

    def add_uv_sphere(name: str, loc, scale, color):
        bpy.ops.mesh.primitive_uv_sphere_add(radius=1.0, location=loc)
        obj = bpy.context.active_object
        obj.name = name
        obj.scale = scale
        mat = bpy.data.materials.new(name=f"M_{name}")
        mat.use_nodes = True
        bsdf = mat.node_tree.nodes.get("Principled BSDF")
        if bsdf:
            bsdf.inputs[0].default_value = (*color, 1.0)
        obj.data.materials.append(mat)
        return obj

    def add_cube(name: str, loc, scale, color):
        bpy.ops.mesh.primitive_cube_add(size=1.0, location=loc)
        obj = bpy.context.active_object
        obj.name = name
        obj.scale = scale
        mat = bpy.data.materials.new(name=f"M_{name}")
        mat.use_nodes = True
        bsdf = mat.node_tree.nodes.get("Principled BSDF")
        if bsdf:
            bsdf.inputs[0].default_value = (*color, 1.0)
        obj.data.materials.append(mat)
        return obj

    exports = [
        ("CHAR_Hunter_proxy", lambda: add_uv_sphere("CHAR_Hunter_proxy", (0, 0, 0.9), (0.4, 0.4, 0.9), (0.25, 0.4, 0.65))),
        ("CHAR_Dummy_proxy", lambda: add_uv_sphere("CHAR_Dummy_proxy", (0, 0, 0.9), (0.45, 0.45, 0.95), (0.75, 0.08, 0.05))),
        ("WPN_Sword_proxy", lambda: add_cube("WPN_Sword_proxy", (0, 0, 0.5), (0.05, 0.05, 0.95), (0.65, 0.68, 0.75))),
        ("WPN_Axe_proxy", lambda: add_cube("WPN_Axe_proxy", (0, 0, 0.35), (0.12, 0.05, 0.7), (0.45, 0.35, 0.28))),
        ("PROP_Crate_proxy", lambda: add_cube("PROP_Crate_proxy", (0, 0, 0.5), (1.0, 1.0, 1.0), (0.4, 0.28, 0.12))),
    ]

    for name, builder in exports:
        clear()
        builder()
        bpy.ops.object.select_all(action="SELECT")
        # Prefer Wavefront OBJ (no numpy/gltf addon deps on minimal Blender builds)
        path = OUT / f"{name}.obj"
        bpy.ops.wm.obj_export(filepath=str(path), export_selected_objects=True)
        print(f"exported {path}")

    # manifest
    manifest = OUT / "MANIFEST.md"
    lines = [
        "# Tribune slice proxy exports",
        "",
        "Generated by tools/scripts/export_slice_proxies.py",
        "Format: OBJ (portable). Import to UE as StaticMesh; scale 100 if units mismatch.",
        "Prefer re-export after art pass; these are greybox-readable proxies.",
        "",
    ]
    for p in sorted(list(OUT.glob("*.obj")) + list(OUT.glob("*.glb")) + list(OUT.glob("*.gltf"))):
        lines.append(f"- `{p.name}` ({p.stat().st_size} bytes)")
    manifest.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {manifest}")


def export_fallback_without_blender() -> None:
    """Minimal glTF JSON boxes so pipeline is non-empty without bpy."""
    # Minimal valid glTF 2.0 triangle as placeholder text marker
    for name in (
        "CHAR_Hunter_proxy",
        "CHAR_Dummy_proxy",
        "WPN_Sword_proxy",
        "WPN_Axe_proxy",
        "PROP_Crate_proxy",
    ):
        # Write a tiny glTF (not binary) so tools can see artifacts exist
        gltf = OUT / f"{name}.gltf"
        gltf.write_text(
            """{
  "asset": {"version": "2.0", "generator": "Tribune export_slice_proxies fallback"},
  "scenes": [{"nodes": [0]}],
  "nodes": [{"mesh": 0, "name": "%s"}],
  "meshes": [{
    "primitives": [{
      "attributes": {"POSITION": 0},
      "indices": 1
    }]
  }],
  "buffers": [{"uri": "data:application/octet-stream;base64,AAAAAAAAAAAAAAAAAAAAAA==", "byteLength": 16}],
  "bufferViews": [
    {"buffer": 0, "byteOffset": 0, "byteLength": 12, "target": 34962},
    {"buffer": 0, "byteOffset": 12, "byteLength": 4, "target": 34963}
  ],
  "accessors": [
    {"bufferView": 0, "componentType": 5126, "count": 1, "type": "VEC3", "max": [0,0,0], "min": [0,0,0]},
    {"bufferView": 1, "componentType": 5123, "count": 1, "type": "SCALAR"}
  ]
}
"""
            % name,
            encoding="utf-8",
        )
        print(f"fallback wrote {gltf}")
    (OUT / "MANIFEST.md").write_text(
        "# Tribune proxies (fallback without bpy)\n\n"
        "Run with Blender for real glb:\n"
        "`blender --background --python tools/scripts/export_slice_proxies.py`\n",
        encoding="utf-8",
    )


def main() -> int:
    try:
        import bpy  # type: ignore  # noqa: F401

        export_with_blender()
    except Exception as exc:  # noqa: BLE001
        print(f"Blender module unavailable ({exc}); writing fallback glTF markers", file=sys.stderr)
        export_fallback_without_blender()
    return 0


if __name__ == "__main__":
    # When executed inside Blender, __name__ may still be __main__
    raise SystemExit(main())
